=== Uduse/e-linguistics/goldcomm/xml/schemas/orthography_profile.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="orthography_profile">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="script" type="scripttype" maxOccurs="unbounded"/>
                <xsd:element name="glyph_inventory" type="glyph_inventorytype" maxOccurs="unbounded"/>                
                <xsd:element name="phoneme_inventory" type="phoneme_inventorytype" maxOccurs="unbounded"/>                
                <xsd:element name="correspondence" type="correspondencetype" maxOccurs="unbounded"/> 
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>    
    <xsd:complexType name="scripttype">
        <xsd:attribute name="name" />        
    </xsd:complexType>
    <xsd:complexType name="glyph_inventorytype">
        <xsd:sequence>
            <xsd:element name="glyph" type="glyphtype" maxOccurs="unbounded"/>
        </xsd:sequence>        
    </xsd:complexType>
    <xsd:complexType name="glyphtype">
        <xsd:attribute name="id" /> 
        <xsd:attribute name="canonicalform" /> 
        <xsd:attribute name="codepoint" /> 
    </xsd:complexType>
    <xsd:complexType name="phoneme_inventorytype">
        <xsd:sequence>
            <xsd:element name="phoneme" type="phonemetype" maxOccurs="unbounded"/>
        </xsd:sequence>        
    </xsd:complexType>
    <xsd:complexType name="phonemetype">
        <xsd:attribute name="id" /> 
    </xsd:complexType>
    <xsd:complexType name="correspondencetype">
        <xsd:sequence>
            <xsd:element name="unit_g2p" type="unit_g2ptype" maxOccurs="unbounded"/>
        </xsd:sequence>        
    </xsd:complexType>
    <xsd:complexType name="unit_g2ptype">
        <xsd:sequence>
            <xsd:element name="grapheme_sequence" type="grapheme_sequencetype" maxOccurs="unbounded"/>
            <xsd:element name="phoneme_sequence" type="phoneme_sequencetype" maxOccurs="unbounded"/>
        </xsd:sequence>    
    </xsd:complexType>
    <xsd:complexType name="grapheme_sequencetype">
        <xsd:attribute name="first" />
        <xsd:attribute name="second" />
    </xsd:complexType>
    <xsd:complexType name="phoneme_sequencetype">
        <xsd:attribute name="first" />
        <xsd:attribute name="second" />
    </xsd:complexType>    
</xsd:schema>

=== Uduse/e-linguistics/goldcomm/xml/xmldata/orthography_profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<orthography_profile 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/orthography_profile.xsd">
	
	<script name="Arabic"/>

	<glyph_inventory>
		<glyph id="1" canonicalform="a" codepoint="0072"/>
		<glyph id="2" canonicalform="b" codepoint="0073"/>
		<glyph id="3" canonicalform="c" codepoint="0074"/>				
	</glyph_inventory>

	<phoneme_inventory>
		<phoneme id="1"/> <!-- need to specify the id matches the glyph id -->
		<phoneme id="2"/>
	</phoneme_inventory>
	
	<correspondence>
		<unit_g2p>
			<grapheme_sequence first="" second=""/>
			<phoneme_sequence first="" second=""/>
		</unit_g2p>
		<unit_p2g>
			<phoneme_sequence first="" second=""/>
			<grapheme_sequence first="" second=""/>
		</unit_p2g>	
	</correspondence>

</orthography_profile>


	<!-- goes in highest level schema, to track provenance-->
<!-- 	<sources>
		<document uri="" author=""/> perhaps a phoible uri
		<tool uri="" author=""/>
		</sources> -->

	<!-- The note element is a  complex type because it contains other elements.
	
	
	<!-- needs rule ordering 
	<parsing_rules> 
		<rule input="" output="" exceptions=""/>
		<exceptions></exceptions> 
		</parsing_rules>-->



<!--
	http://www.xfront.com/eXtreme-eXtensibility.html
	
	<element name="River">
	<complexType>	
	<sequence>
	<any namespace="##targetNamespace" maxOccurs="unbounded"/>
	</sequence>
	<attribute name="id" type="ID" use="required"/>
	</complexType>
	</element>
	<element name="Length" type="string"/>
	<element name="StartingLocation" type="string"/>
	<element name="EndingLocation" type="string"/>
	
	- no restrictions on the contents of River
	- initial vocabulary - Length, StartingLocation, etc.
	- no restriction on the ordering of elements?
	- additional XML Web pages whose vocabulary extends the initial vocabulary need schemas created for them
	
	SCOTT:
	- do we want restrictions on the contents of "orthographic_profile" (or "phonetic_profile", etc.)
	- i need to get familiar with the namespacing schema that we're following
	
	Orthographic profile
	
	Metadata
	URI
	language code
	author
	date
	script
	encoding
	font
	
	Glyph Inventory (Unicode characters)
	U+0073
	U+0074
	U+0069
	U+0076
	
	
	Grapheme-to-phoneme correspondences
	U+0067 U+0079 <dy> -> U+02A4 /Ê¤/
	
	Phoneme Inventory (or a derivable method for it since we have the G2P correspondences)
	include known parsing ambiguities?
	statistics?
	
	Parsing rules
	<dy> -> <dy>  (not <d> and <y> as separate graphemes/phonemes)
	
	List known exceptions and rules for disambiguation when possible?
	e.g. <kidya> 'waterfall' is /kid.ya/ but it's the only example (or classes of examples) in the language
	
	
-->
